### ISSUE TITLE
render form in twig (documentation request)

### ISSUE THREAD

**Issue by 24HOURSMEDIA** [Dolphiq/craft3-forms#10]
The plugin lacks support for rendering forms in twig, which is not good for violation of concerns and unhandy for the designers I work with.

It is very easily accomplished though; here's some code I use (which is quite generic and could be reused in any formView)
I hope this piece of documentation is useful for some developers using this **great plugin**.

For rendering a dolphiq form in twig:

(1) define your forms as usual (i.e. in /forms/myForm/....)
(2) set up your view so (it assumes an attribute agree_privacy in the Form)

```php
// /forms/myForm/myFormView.php

use yii\widgets\ActiveForm;
use yii\widgets\Pjax;
use craft\web\View;

try {
    Pjax::begin(['enablePushState' => false, 'id' => 'pjax-' . $handle]);
    $form = ActiveForm::begin([
        'action' => \craft\helpers\UrlHelper::actionUrl('dolphiq-craft3-forms/main/index', ['handle' => $handle, 'params' => Craft::$app->getRequest()->getParam('params')]),
        'method' => 'POST',
        'options' => [
            'data-pjax' => true,
        ],
    ]);

    // pass view data to the form template files. add more variables as required, they are accessible.
    // i.e. in the template, use:
    // {{ form.field(model, 'agree_privacy').checkbox }}
    /* @var $view View */
    $view = Craft::$app->view;
    // get params passed from the twig tag used to invoke the form, i.e. {{ dolphiqForm('myForm', {my_data: 'hello world'}) | raw }}
    $params = json_decode(Craft::$app->getRequest()->getParam('params', '[]'), true);
    $params = is_array($params) ? $params : [];
    // add additional parameters to pass to the twig form view
    $viewData = array_merge(
        $params,
        [
            'handle' => $handle,
            'model' => $model,
            'form' => $form
        ]
    );
    // place the form in /templates/ where your other twig files reside
    echo $view->renderPageTemplate('_dolphiqform/' . $handle . '/form.twig', $viewData);
    ActiveForm::end();
    Pjax::end();
} catch (\Exception $e) {
    // you can choose to display errors in devmode here.
    //$e->getMessage();
    // or, for PROD:
    throw $e;
}
```

Now you can render your form in a Twig file your create in /templates/_dolphiqforms/myForm/form.twig:

```twig
{# /templates/_dolphiqforms/myForm/form.twig #}

<h3>My Form</h3>

{{ form.field(model, 'agree_privacy').checkbox | raw }}

<button type="submit">
    {{ 'Send Request' | t }}
</button>

```

**Comment by Luuc15** [comment]
Hi, 

Thanks for researching on how to use the form with the twig templates.
Your solution seems like a good one that everybody can use if they want to build there forms with twig.
However this plugin was specifically build to be able to create forms like you would do when using the Yii framework.

For documentation on how to use the Yii framework views see: https://www.yiiframework.com/doc/guide/2.0/en/input-forms and https://www.yiiframework.com/doc/guide/2.0/en/structure-views
