### ISSUE TITLE
Craft 3.5 support

### ISSUE THREAD

**Issue by stevebombedout** [Dolphiq/craft3-forms#24]
Hi guys - I see it's been a while since the last update and I've been experiencing issues with the form not loading since upgrading to Craft 3.5.

Exception 'Error' with message 'Call to a member function getAcceptsJson() on string' in .../vendor/craftcms/cms/src/web/Controller.php:183

Forms were working fine prior to the update.

**Comment by devotoare** [comment]
@richcoopa is it possible to deploy this fix to a new version?
