### ISSUE TITLE
Customer mail not sent

### ISSUE THREAD

**Issue by StijnCoolen** [Dolphiq/craft3-forms#4]
The customer mail is not sent when I provide a 'contactMailCustomer', only when i I add a 'contactMailOwner' a mail is sent to both the customer and owner. The right subject is used but the text of both mails is the same. (content of 'contactMailOwner 'is also sent to the customer).

Also both mails are delivered twice.

I am testing with Mailtrap. Using Craft Personal 3.0.0-RC15

**Comment by Luuc15** [comment]
This is a bug in the mainController line 74. Fixed in development version and will be released soon
