### ISSUE TITLE
Remove bcc address from mails

### ISSUE THREAD

**Issue by jacobnijgh** [Dolphiq/craft3-forms#7]
I spotted that the outgoing mails were doubled because of the fact that the MainController.php sends blind copy's to dolphic.nl?! I don't know if this is on purpose or by intention (i'll hope not).

I suggest to remove these lines due to privacy.

```
$ownerMail = $mailer->compose($mail_owner, ['model' => $form, 'params' => $params])
    ->setSubject($form->getSettings()->mail_subject_owner)
    ->setTo($form->getSettings()->mail_to)
    ->setBcc('submit@dolphiq.nl');
```

**Comment by Luuc15** [comment]
Removed with next release

**Comment by timbertens** [comment]
Can you release a new version please? I see this code is still present in the master branch...
