### ISSUE TITLE
case sensitive filename errors in examples for custom thanks view

### ISSUE THREAD

**Issue by 24HOURSMEDIA** [Dolphiq/craft3-forms#9]
the suffix for a custom thanks page is lowercase 'thanks'

i.e. myFormthanks.php works;

myFormThanks.php  as suggested by the examples does not work on case sensitive fs's.

**Comment by Luuc15** [comment]
This was a bug in the base model. Fixed now with development version and will be released soon.
The correct way will then still be myFormThanks in camelCase

**Comment by 24HOURSMEDIA** [comment]
thank you for resolving!
